security:
  encoders:
    App\Entity\User:
      algorithm: argon2i

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      logout:
        path: app_logout
      form_login:
        login_path: app_login
        check_path: app_login
        provider: app_user_provider

  access_control:
    - { path: ^/profile/edit, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/profile, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
